# Generated by Django 5.1.6 on 2025-03-06 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MLAAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_since',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('AIEngineer', 'AI Engineer'), ('FinanceDepartment', 'Finance Department'), ('EndUser', 'End User')], default='EndUser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
