services:
  db:
      image: postgres:15
      restart: unless-stopped     
      environment:
        - POSTGRES_DB= ${DB_NAME}
        - POSTGRES_USER= ${DB_USER}
        - POSTGRES_PASSWORD= ${DB_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - desd-ai:/var/lib/postgresql/data

  api:
    image: desd-ai:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  desd-ai: