# Generated by Django 5.0.2 on 2025-03-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_invoice_payment_url_invoice_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('End User', 'End User'), ('Admin', 'Admin'), ('AI Engineer', 'AI Engineer'), ('Finance Team', 'Finance Team')], default='End User', max_length=50),
        ),
    ]
