# Generated by Django 5.1.6 on 2025-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(default='MLAAS Service Invoice', max_length=500),
        ),
    ]
