# Generated by Django 5.1.6 on 2025-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mlmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='accuracy',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(max_length=50),
        ),
    ]
