# Generated by Django 5.1.6 on 2025-03-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoice_description'),
        ('api', '0008_prediction_is_checked'),
    ]

    operations = [
    ]
