# Generated by Django 5.1.6 on 2025-04-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20250327_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='requires_scaling',
            field=models.BooleanField(default=False),
        ),
    ]
