# Generated by Django 5.1.6 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mlmodel_requires_scaling'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=255)),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('status_code', models.IntegerField(help_text='HTTP status code')),
                ('error', models.BooleanField(default=False, help_text='Whether this request resulted in an error')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this metric was recorded')),
            ],
            options={
                'verbose_name': 'API Metric',
                'verbose_name_plural': 'API Metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
